# Generated by Django 5.0.3 on 2024-03-29 12:50

import netresume.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netresume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prj_name', models.CharField(max_length=200)),
                ('github_url', models.CharField(max_length=200)),
                ('demo_video_url', models.CharField(max_length=200)),
                ('prj_screenshot', models.ImageField(upload_to=netresume.models.image_upload_path)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(upload_to=netresume.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='skill',
            name='img',
            field=models.ImageField(upload_to=netresume.models.image_upload_path),
        ),
    ]
