# Generated by Django 5.0.3 on 2024-03-29 16:38

import netresume.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netresume', '0002_project_alter_course_img_alter_skill_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(blank=True, upload_to=netresume.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='prj_screenshot',
            field=models.ImageField(blank=True, upload_to=netresume.models.image_upload_path),
        ),
    ]
